name: Release v1
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: |
          git tag -f v1
          git push -f origin v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
